############################
# --- Required options --- #
############################

# Name of website
name: placeholder
title: null

# Your name to show in the footer
author: @drasbaek & @MinaAlmasi
